//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AwqafZakatEntities : DbContext
    {
        public AwqafZakatEntities()
            : base("name=AwqafZakatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdminRegistration> tblAdminRegistrations { get; set; }
        public virtual DbSet<tblEducationLevel> tblEducationLevels { get; set; }
        public virtual DbSet<tblFamilyDeletion> tblFamilyDeletions { get; set; }
        public virtual DbSet<tblFamilymemberDetail> tblFamilymemberDetails { get; set; }
        public virtual DbSet<tblFamilyPropertyDetail> tblFamilyPropertyDetails { get; set; }
        public virtual DbSet<tblFamilyRegistration> tblFamilyRegistrations { get; set; }
        public virtual DbSet<tblFamilySpecialNeed> tblFamilySpecialNeeds { get; set; }
        public virtual DbSet<tblFamilyTransfer> tblFamilyTransfers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblFamilyIncomeExpense> tblFamilyIncomeExpenses { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
    }
}
