//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblAdminRegistration
    {
        public int adminRegistrationID { get; set; }
        [DisplayName("—ﬁ„ «·„‘—› ›Ì «·‰Ÿ«„")]
        [Required(ErrorMessage = "This field is required")]
        public int administratorNumber { get; set; }
        [DisplayName("  «—ÌŒ «· ”ÃÌ· („) ")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> registrationDateHijri { get; set; }
        [DisplayName("  «—ÌŒ «· ”ÃÌ· (Â) ")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> registrationDate { get; set; }
        [DisplayName("«·«”‹‹‹„ «·À·«ÀÌ Ê«·ﬁ»Ì·…:")]
        [Required(ErrorMessage = "This field is required")]
        public string tripleNameTribe { get; set; }
        [DisplayName("«·—ﬁ„ «·„‹‹‹‹‹‹‹‹‹œ‰Ì:")]
        [Required(ErrorMessage = "This field is required")]
        public string civilNumber { get; set; }
        [DisplayName("—ﬁ„ «·”ﬂ…:")]
        [Required(ErrorMessage = "This field is required")]
        public string railNumber { get; set; }
        [DisplayName("—ﬁ„ «·„‰“·:")]
        [Required(ErrorMessage = "This field is required")]
        public string homeNumber { get; set; }
        [DisplayName("«”„ √ﬁ—» „”Ã‹‹‹‹‹œ „‰ «·„‰“·:")]
        [Required(ErrorMessage = "This field is required")]
        public string mosqueName { get; set; }
        [DisplayName("«”„ «·„‰ÿﬁ… √Ê «·ﬁ—Ì… «·„”ƒÊ· ⁄‰Â«:")]
        [Required(ErrorMessage = "This field is required")]
        public string regionName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string supervisorWhatsapp { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string supervisorOfficePhone { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string supervisorHomePhone { get; set; }
        [DisplayName("«”„ «Õœ «·«ﬁ«—»:")]
        [Required(ErrorMessage = "This field is required")]
        public string relativeName { get; set; }
        [DisplayName("—ﬁ„ «·Â« ›:")]
        [Required(ErrorMessage = "This field is required")]
        public string relativePhone { get; set; }
        [DisplayName("«”„ „”«⁄œ «·„‘—›:")]
        // [Required(ErrorMessage = "This field is required.")]
        public string assistantName { get; set; }
        [DisplayName("—ﬁ„ «·Â« ›:")]
        [Required(ErrorMessage = "This field is required")]
        public string assistantPhone { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
        [Required(ErrorMessage = "This field is required")]
        public string adminIdCard { get; set; }
        [NotMapped]
        public HttpPostedFileBase adminImageUpload { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
        [Required(ErrorMessage = "This field is required")]
        public string assistantIdCard { get; set; }
        [NotMapped]
        public HttpPostedFileBase assistantImageUpload { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string chairmanName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string vchairmanName { get; set; }
        [DisplayName("„·«ÕŸ…:")]
        [Required(ErrorMessage = "This field is required")]
        public string notes { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
        [Required(ErrorMessage = "This field is required")]
        public string hardcopyAttach { get; set; }
        [NotMapped]
        public HttpPostedFileBase hardcopyImageUpload { get; set; }

        public tblAdminRegistration()
        {
            adminIdCard = "~/AppFiles/Images/default.png";
            assistantIdCard = "~/AppFiles/Images/default.png";
            hardcopyAttach = "~/AppFiles/Images/default.png";
        }
    }
}
