//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFamilymemberDetail
    {
        public int memberID { get; set; }
        public Nullable<int> familyRegID { get; set; }
        public Nullable<int> educationLevelID { get; set; }
        public string familymembername { get; set; }
        public string memberCivilNumber { get; set; }
        public string @case { get; set; }
        public string relativerelation { get; set; }
        public string educationalInstitute { get; set; }
        public string memberNotes { get; set; }
    
        public virtual tblEducationLevel tblEducationLevel { get; set; }
        public virtual tblFamilyRegistration tblFamilyRegistration { get; set; }
    }
}
