//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFamilyPropertyDetail
    {
        public int familyPropertyDetailID { get; set; }
        public Nullable<int> familyRegID { get; set; }
        public string familyProperty { get; set; }
        public Nullable<int> numOfProperty { get; set; }
    
        public virtual tblFamilyRegistration tblFamilyRegistration { get; set; }
    }
}
