//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblFamilyTransfer
    {
        public int familyTransferID { get; set; }
        // [DisplayName("—ﬁ„ «·√”—… ›Ì «·‰Ÿ«„")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> familyRegID { get; set; }
        [DisplayName("  «—ÌŒ «· ”ÃÌ· (Â) ")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> transferDate { get; set; }
        [DisplayName(" ≈Õœ«ÀÌ«  «·„Êﬁ⁄ «·ÃœÌœ ÃÌ . »Ì .√” ")]
        // [Required(ErrorMessage="This field is required.")]
        public Nullable<int> ecoordinate { get; set; }
        public Nullable<int> ncoordinate { get; set; }
        [DisplayName(" «·„‰ÿﬁ… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldRegion { get; set; }
        [DisplayName(" «·„‰ÿﬁ… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string newRegion { get; set; }
        [DisplayName(" «·ﬁ—Ì… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldVillage { get; set; }
        [DisplayName(" «·ﬁ—Ì… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string newVillage { get; set; }
        [DisplayName(" —ﬁ„ «·”ﬂ…: ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldRailNumber { get; set; }
        [DisplayName(" —ﬁ„ «·”ﬂ…: ")]
        [Required(ErrorMessage = "This field is required")]
        public string newRailNumber { get; set; }
        [DisplayName(" —ﬁ„ «·„‰“·: ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldHomeNumber { get; set; }
        [DisplayName(" —ﬁ„ «·„‰“·: ")]
        [Required(ErrorMessage = "This field is required")]
        public string newHomeNumber { get; set; }
        [DisplayName(" «”„ √ﬁ—» „”Ãœ „‰ «·»Ì  : ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldMosque { get; set; }
        [DisplayName(" «”„ √ﬁ—» „”Ãœ „‰ «·»Ì   ")]
        [Required(ErrorMessage = "This field is required")]
        public string newMosque { get; set; }
        [DisplayName(" √—ﬁ«„ «·ÂÊ« › «·ﬁœÌ„… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldMobile { get; set; }
        [DisplayName("  ")]
        [Required(ErrorMessage = "This field is required")]
        public string oldTelephone { get; set; }
        [DisplayName(" √—ﬁ«„ ÂÊ« › ÃœÌœ… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string newMobile { get; set; }
        [DisplayName(" √—ﬁ«„ «·ÂÊ« › «·ﬁœÌ„… : ")]
        [Required(ErrorMessage = "This field is required")]
        public string newTelephone { get; set; }
        [DisplayName(" «”„ «·„‘—› «·”«»ﬁ : ")]
        [Required(ErrorMessage = "This field is required")]
        public string prevAdmin { get; set; }
        [DisplayName(" —ﬁ„ «·Â« ›: ")]
        [Required(ErrorMessage = "This field is required")]
        public string prevAdminPhone { get; set; }
        [DisplayName(" «”„ «·„‘—› «·Õ«·Ì : ")]
        [Required(ErrorMessage = "This field is required")]
        public string currentAdmin { get; set; }
        [DisplayName(" —ﬁ„ «·Â« ›: ")]
        [Required(ErrorMessage = "This field is required")]
        public string currentAdminPhone { get; set; }
        // [DisplayName("  «—ÌŒ «· ”ÃÌ· (Â) ")]
        [Required(ErrorMessage = "This field is required.")]
        public string chairmanName { get; set; }
        // [DisplayName("  «—ÌŒ «· ”ÃÌ· (Â) ")]
        [Required(ErrorMessage = "This field is required.")]
        public string vchairmanName { get; set; }
        [DisplayName(" »ÿ«ﬁ… «·ÂÊÌ… ")]
        [Required(ErrorMessage = "This field is required")]
        public string electricityAttach { get; set; }
        [NotMapped]
        public HttpPostedFileBase electricityImageUpload { get; set; }
        [DisplayName(" »ÿ«ﬁ… «·ÂÊÌ… ")]
        [Required(ErrorMessage = "This field is required")]
        public string hardcopyAttach { get; set; }
        [NotMapped]
        public HttpPostedFileBase hardcopyImageUpload { get; set; }
        [DisplayName("„·«ÕŸ…:")]
        [Required(ErrorMessage = "This field is required")]
        public string notes { get; set; }

        public tblFamilyTransfer()
        {
            hardcopyAttach = "~/AppFiles/Images/default.png";
            electricityAttach = "~/AppFiles/Images/default.png";
        }

        public virtual tblFamilyRegistration tblFamilyRegistration { get; set; }
    }
}
