//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblFamilyDeletion
    {
        public int familyDeletionID { get; set; }
        [DisplayName(" —ﬁ„ «·√”—… ›Ì «·‰Ÿ«„: ")]
        //[Required(ErrorMessage = "This field is required")]
        public Nullable<int> familyRegID { get; set; }
        [DisplayName(" «—ÌŒ «· ”ÃÌ· (Â) ")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> deletionDate { get; set; }
        [DisplayName("«”„ «·„”ƒÊ· ⁄‰ «·√”—…:")]
        [Required(ErrorMessage = "This field is required")]
        public string familyName { get; set; }
        [DisplayName("«”»«» «·Õ–›: ")]
        // [Required(ErrorMessage = "This field is required")]
        public string deletionReason { get; set; }
        [DisplayName("œŒ· «·√”—… ⁄‰œ «·Õ–›: ")]
        [Required(ErrorMessage = "This field is required")]
        public Nullable<decimal> familyIncomeAtDel { get; set; }
        [DisplayName("«”„ «·„‘—›: ")]
        [Required(ErrorMessage = "This field is required")]
        public string adminName { get; set; }
        // [DisplayName(" ")]
        [Required(ErrorMessage = "This field is required")]
        public string chairmanName { get; set; }
        //[DisplayName(" ")]
        [Required(ErrorMessage = "This field is required")]
        public string vchairmanName { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
        [Required(ErrorMessage = "This field is required")]
        public string hardcopyAttach { get; set; }
        [NotMapped]
        public HttpPostedFileBase hardcopyImageUpload { get; set; }

        public tblFamilyDeletion()
        {
            hardcopyAttach = "~/AppFiles/Images/default.png";
        }

        public virtual tblFamilyRegistration tblFamilyRegistration { get; set; }
    }
}
