//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblFamilyRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFamilyRegistration()
        {
            this.tblFamilyDeletions = new HashSet<tblFamilyDeletion>();
            this.tblFamilymemberDetails = new HashSet<tblFamilymemberDetail>();
            this.tblFamilyPropertyDetails = new HashSet<tblFamilyPropertyDetail>();
            this.tblFamilySpecialNeeds = new HashSet<tblFamilySpecialNeed>();
            this.tblFamilyTransfers = new HashSet<tblFamilyTransfer>();
            this.tblFamilyIncomeExpenses = new HashSet<tblFamilyIncomeExpense>();

            document = "~/AppFiles/Images/default.png";
            hardcopyAttach = "~/AppFiles/Images/default.png";
        }
    
        public int familyRegID { get; set; }
        [DisplayName("—ﬁ„ «·√”—… ›Ì «·‰Ÿ«„")]
       // [Required(AllowEmptyStrings = false, ErrorMessage = "This field is required")]
        // [Required(ErrorMessage = "This field is required")]
        public int familyRegNumber { get; set; }
        [DisplayName(" «—ÌŒ «· ”ÃÌ· („)")]
       // [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> registrationDateHijri { get; set; }
        [DisplayName(" «—ÌŒ «· ”ÃÌ· (Â)")]
      //  [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> registrationDate { get; set; }
        [DisplayName(" «—ÌŒ «· ÕœÌÀ «·ﬁ«œ„")]
     //   [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> nextUpdationDate { get; set; }
        [DisplayName("≈Õœ«ÀÌ«  «·„Êﬁ⁄ ÃÌ . »Ì .√”")]
      //  [Required(ErrorMessage = "This field is required")]
        public Nullable<int> ecoordinate { get; set; }
        // [DisplayName("")]
        // // [Required(ErrorMessage = "This field is required")]
        public Nullable<int> ncoordinate { get; set; }
        [DisplayName("«·«”„ «·À·«ÀÌ Ê«·ﬁ»Ì·…:")]
       // [Required(ErrorMessage = "This field is required")]
        public string tripleNameTribe { get; set; }
        [DisplayName(" «—ÌŒ «·„Ì·«œ :")]
       // [Required(ErrorMessage = "This field is required")]
        public Nullable<System.DateTime> dob { get; set; }
        [DisplayName("’·… «·ﬁ—«»… :")]
       // [Required(ErrorMessage = "This field is required")]
        public string relationshipOfKinship { get; set; }
        [DisplayName("«·„ƒÂ· «· ⁄·Ì„Ì :")]
       // [Required(ErrorMessage = "This field is required")]
        public string education { get; set; }
        [DisplayName("«·—ﬁ„ «·„œ‰Ì:")]
       // [Required(ErrorMessage = "This field is required")]

        public string civilNumber { get; set; }
        [DisplayName("«·ÊŸÌ›… :")]
       // [Required(ErrorMessage = "This field is required")]
        public string occupation { get; set; }
        [DisplayName("«·Õ«·… «·«Ã „«⁄Ì… :")]
      //  [Required(ErrorMessage = "This field is required")]
        public string socialStatus { get; set; }
        [DisplayName("«·„‰ÿﬁ… :")]
     //   [Required(ErrorMessage = "This field is required")]
        public string region { get; set; }
        [DisplayName("«·ﬁ—Ì… :")]
      //  [Required(ErrorMessage = "This field is required")]
        public string village { get; set; }
        [DisplayName("⁄œœ √›—«œ «·«”‹‹—… :")]
       // [Required(ErrorMessage = "This field is required")]
        public Nullable<int> numberOfFamilyMember { get; set; }
        [DisplayName("—ﬁ„ «·”ﬂ… :")]
      //  [Required(ErrorMessage = "This field is required")]
        public string railwayNumber { get; set; }
        [DisplayName("«”„ √ﬁ—» „”Ãœ „‰ «·»Ì  :")]
      //  [Required(ErrorMessage = "This field is required")]
        public string mosque { get; set; }
        [DisplayName("—ﬁ„ «·„‰“· :")]
      //  [Required(ErrorMessage = "This field is required")]
        public string houseNumber { get; set; }
        [DisplayName("«·Ã‰”Ì… :")]
       // [Required(ErrorMessage = "This field is required")]
        public string nationality { get; set; }
        [DisplayName("√—ﬁ«„ «·ÂÊ« › :")]
       // [Required(ErrorMessage = "This field is required")]
        public string officePhone { get; set; }
        //[DisplayName("")]
      //  [Required(ErrorMessage = "This field is required")]
        public string homePhone { get; set; }
        // [DisplayName("")]
     //   [Required(ErrorMessage = "This field is required")]
        public string whatsapp { get; set; }
        [DisplayName("«”‹‹‹‹‹‹‹‹„ «·»‰ﬂ:")]
      //  [Required(ErrorMessage = "This field is required")]
        public string bank { get; set; }
        [DisplayName("—ﬁ„ «·Õ”‹‹‹«»:")]
       // [Required(ErrorMessage = "This field is required")]
        public string accountNumber { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
      //  [Required(ErrorMessage = "This field is required")]
        public string document { get; set; }
        [NotMapped]
        /* Multifile upload : take files as list */
        public List<HttpPostedFileBase> ImageUpload { get; set; }
        [DisplayName("„·«ÕŸ« : ")]
       // [Required(ErrorMessage = "This field is required")]
        public string notes { get; set; }
        [DisplayName("Â· ÌÊÃœ ›Ì «·√”—… Ì Ì„ø")]
        public Nullable<int> numberOfOrphan { get; set; }
        [DisplayName("Â·  ” ·„ «·√”—… ≈⁄«‰… „‰ ÃÂ… √Œ—Ïø ")]
       // [Required(ErrorMessage = "This field is required")]
        public bool receiveSubsidy { get; set; }
        [DisplayName("«·œÊ·… Ê‰Ê⁄ «·„”«⁄œ…: ")]
        // [Required(ErrorMessage = "This field is required")]
        public string subsidyState { get; set; }
        [DisplayName("Â· ÌÊÃœ ›Ì «·√”—… „‰ –ÊÌ «·«Õ Ì«Ã«  «·Œ«’… ")]
        // // [Required(ErrorMessage = "This field is required")]
        public Nullable<int> numberOfSpecialNeed { get; set; }
        [DisplayName("«·«”‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹„")]
       // [Required(ErrorMessage = "This field is required")]
        public string supervisorName { get; set; }
        [DisplayName("«·„‰ÿﬁ… Ê«·ﬁ—Ì… ")]
       // [Required(ErrorMessage = "This field is required")]
        public string supervisorAreaVillage { get; set; }
        [DisplayName("—ﬁ„ «·Â« ›: ")]
       // [Required(ErrorMessage = "This field is required")]
        public string supervisorPhone { get; set; }
        [DisplayName("«·„”‹‹‹‹‹‹‹‹‹‹‹‹‹Ãœ")]
       // [Required(ErrorMessage = "This field is required")]
        public string supervisorMosque { get; set; }
        [DisplayName("«·„·«ÕŸ‹‹‹‹‹‹«  ")]
      //  [Required(ErrorMessage = "This field is required")]
        public string supervisorObservedData { get; set; }
        public Nullable<decimal> familyPerCapitaIncome { get; set; }
        [DisplayName("«·«”—… €Ì— „” Õﬁ… ")]
      //  [Required(ErrorMessage = "This field is required")]
        public Nullable<bool> isFamilyWorthy { get; set; }
        [DisplayName(" «·„·«ÕŸ« : ")]
      //  [Required(ErrorMessage = "This field is required")]
        public string officialNotes { get; set; }
      //  [Required(ErrorMessage = "This field is required")]
        public string chairmanName { get; set; }
      //  [Required(ErrorMessage = "This field is required")]
        public string vchairmanName { get; set; }
        [DisplayName("≈—›«ﬁ »ÿ«ﬁ… «·ÂÊÌ…")]
     //   [Required(ErrorMessage = "This field is required")]
        public string hardcopyAttach { get; set; }
        [NotMapped]
        public HttpPostedFileBase hardcopyImageUpload { get; set; }
        // [Required(ErrorMessage = "This field is required")]  
        public string status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilyDeletion> tblFamilyDeletions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilymemberDetail> tblFamilymemberDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilyPropertyDetail> tblFamilyPropertyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilySpecialNeed> tblFamilySpecialNeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilyTransfer> tblFamilyTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFamilyIncomeExpense> tblFamilyIncomeExpenses { get; set; }
    }
}
