//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSetting
    {
        public int settingsID { get; set; }
        [DisplayName("Settings Name")]
        [Required(ErrorMessage = "This field is required")]
        public string settingsName { get; set; }
        [DisplayName("Value")]
        [Required(ErrorMessage = "This field is required")]
        public string value { get; set; }
        [DisplayName("Notes")]
        [Required(ErrorMessage = "This field is required")]
        public string notes { get; set; }
    }
}
