//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwqafZakat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblUser
    {
        public int userID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string fname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string lname { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string userName { get; set; }

        public string email { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Confirm password:")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string confirmPassword { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
