CREATE TABLE [dbo].[tblFamilyRegistrations] (
    [familyRegID]            INT            IDENTITY (1, 1) NOT NULL,
    [familyRegNumber]        INT          unique  NOT NULL,
    [registrationDateHijri]  DATE           NULL,
    [registrationDate]       DATE           NULL,
    [nextUpdationDate]       DATE           NULL,
    [ecoordinate]            INT            NULL,
    [ncoordinate]            INT            NULL,
    [tripleNameTribe]        NVARCHAR (100) NULL,
    [dob]                    DATE           NULL,
    [relationshipOfKinship]  NVARCHAR (50)  NULL,
    [education]              NVARCHAR (50)  NULL,
    [civilNumber]            NVARCHAR (50)  NOT NULL,
    [occupation]             NVARCHAR (50)  NULL,
    [socialStatus]           NVARCHAR (50)  NULL,
    [region]                 NVARCHAR (50)  NULL,
    [village]                NVARCHAR (50)  NULL,
    [numberOfFamilyMember]   INT            NULL,
    [railwayNumber]          NVARCHAR (50)  NULL,
    [mosque]                 NVARCHAR (100) NULL,
    [houseNumber]            NVARCHAR (50)  NULL,
    [nationality]            NVARCHAR (50)  NULL,
    [officePhone]            NVARCHAR (50)  NULL,
    [homePhone]              NVARCHAR (50)  NULL,
    [whatsapp]               NVARCHAR (50)  NULL,
    [bank]                   NVARCHAR (100) NULL,
    [accountNumber]          NVARCHAR (50)  NULL,
    [document]               NVARCHAR (255) NULL,
    [notes]                  NVARCHAR (MAX) NULL,
    [numberOfOrphan]         INT            NULL,
    [receiveSubsidy]         BIT            NOT NULL,
    [subsidyState]           NVARCHAR (255) NULL,
    [numberOfSpecialNeed]    INT            NULL,
    [supervisorName]         NVARCHAR (100) NULL,
    [supervisorAreaVillage]  NVARCHAR (255) NULL,
    [supervisorPhone]        NVARCHAR (50)  NULL,
    [supervisorMosque]       NVARCHAR (100) NULL,
    [supervisorObservedData] NVARCHAR (MAX) NULL,
    [familyPerCapitaIncome]  DECIMAL (18)   NULL,
    [isFamilyWorthy]         BIT            NULL,
    [officialNotes]          NVARCHAR (MAX) NULL,
    [chairmanName]           NVARCHAR (100) NULL,
    [vchairmanName]          NVARCHAR (100) NULL,
    [hardcopyAttach]         NVARCHAR (255) NULL,
    [status]                 CHAR (1)       NULL,
    PRIMARY KEY CLUSTERED ([familyRegID] ASC)
);

